### ISSUE TITLE
IllegalArgumentException from JDT compiler when running compare

### ISSUE THREAD

**Issue by szabta89** [SpoonLabs/gumtree-spoon-ast-diff#122]
I would like to use gumtree spoon in a Scala project. At this point, I really just wanted to try out the project, so I used code as shown below:
```
new AstComparator().compare(file1, file2)
```
When this code gets executed, I get the following exception
```
java.lang.IllegalArgumentException: Unrecognized option : -1.8
	at org.eclipse.jdt.internal.compiler.batch.Main.configure(Main.java:2631)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:401)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:362)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:330)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:113)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:96)
	at gumtree.spoon.AstComparator.getCtType(AstComparator.java:131)
	at gumtree.spoon.AstComparator.getCtType(AstComparator.java:122)
	at gumtree.spoon.AstComparator.compare(AstComparator.java:94)
```

Do you have any idea what am I doing wrong? Thanks for any help.

**Comment by szabta89** [comment]
Interestingly, if I run the gumtree-spoon.jar (that is hosted in maven central https://mvnrepository.com/artifact/fr.inria.gforge.spoon.labs/gumtree-spoon-ast-diff/1.24)  simply in the command line via `java -jar`, then diffs can be computed.

**Comment by monperrus** [comment]
It seems like a classpath problem (wrong version of JDT taken).

Which jar-with-dependencies do you use?

**Comment by szabta89** [comment]
I used the one from the top of this list: https://repo1.maven.org/maven2/fr/inria/gforge/spoon/labs/gumtree-spoon-ast-diff/1.24/

**Comment by szabta89** [comment]
Yes, you were right. I pulled in gumtree spoon via gradle among other things, and this made the JDT compiler be available with multiple versions. Then, when running gumtree, the wrong version was picked up. Sorry for the hassle, this issue can be closed.

**Comment by monperrus** [comment]
Perfect!
