### ISSUE TITLE
Problems while executing gumtree

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/gumtree-spoon-ast-diff#137]
I have successfully built the project locally but I am unable to execute the jar files.

I passed two Java files like this:
```bash
java -cp target/gumtree-spoon-ast-diff-SNAPSHOT-jar-with-dependencies.jar gumtree.spoon.AstComparator ~/Desktop/diffmin/output/3b748cb/DeploymentRepository.java/prev_commit.java ~/Desktop/diffmin/output/3b748cb/DeploymentRepository.java/this_commit.java
```
I am getting the following error
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at spoon.support.StandardEnvironment.<init>(StandardEnvironment.java:99)
        at gumtree.spoon.AstComparator.createFactory(AstComparator.java:84)
        at gumtree.spoon.AstComparator.getCtType(AstComparator.java:126)
        at gumtree.spoon.AstComparator.getCtType(AstComparator.java:122)
        at gumtree.spoon.AstComparator.compare(AstComparator.java:94)
        at gumtree.spoon.AstComparator.main(AstComparator.java:160)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
        at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:576)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:601)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:588)
        at spoon.Launcher.<clinit>(Launcher.java:589)
        ... 6 more
```

Running the application with incorrect number of parameters (I just passed one file):
```
java -cp target/gumtree-spoon-ast-diff-SNAPSHOT-jar-with-dependencies.jar gumtree.spoon.AstComparator ~/Desktop/diffmin/output/3b748cb/DeploymentRepository.java/prev_commit.java 
```
Returns the following output so I think I have setup the project correctly.
```
Usage: DiffSpoon <file_1>  <file_2>
```

Can anyone help me how can I use the project to compute diff scripts between two Java files?

**Comment by monperrus** [comment]
This is due to the underlying logging library. An implementation library is missing.

What logging jars do you have in your classpath? (`*log4j*`? `*slfj*?` `*logback*`?)

**Comment by algomaster99** [comment]
@monperrus I think the entire project uses `log4j` and even the error message is thrown because of this logger.

**Comment by algomaster99** [comment]
@monperrus I found a solution to this problem but I don't know how to incorporate it. Please let me know if you have any idea. https://stackoverflow.com/questions/52953483/logmanager-getlogger-is-unable-to-determine-class-name-on-java-11

**Comment by algomaster99** [comment]
Downgrading Java to version 8 works for me.

**Comment by algomaster99** [comment]
@monperrus Any idea how can we fix this so that this project runs on Java 11 as well?
