### ISSUE TITLE
Log4j error when using the lib 

### ISSUE THREAD

**Issue by Symbolk** [SpoonLabs/gumtree-spoon-ast-diff#150]
I am importing the gumtree-spoon-ast-diff into my project in build.gradle:

```
    implementation 'fr.inria.gforge.spoon.labs:gumtree-spoon-ast-diff:1.30'

```

However, when I run my program, it reports the following error:

```
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException:  (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:158)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:672)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.log4j12.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
	at org.slf4j.log4j12.Log4j12ServiceProvider.initialize(Log4j12ServiceProvider.java:35)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:152)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:418)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:404)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:353)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:379)
	at edu.pku.code2graph.gen.Generators.<init>(Generators.java:50)
	at edu.pku.code2graph.gen.Generators.getInstance(Generators.java:56)
	at edu.pku.code2graph.diff.cochange.ChangeLint.lambda$initGenerators$0(ChangeLint.java:42)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at edu.pku.code2graph.diff.cochange.ChangeLint.initGenerators(ChangeLint.java:39)
	at edu.pku.code2graph.diff.cochange.ChangeLint.<clinit>(ChangeLint.java:34)
```

So I debugged it and found that it seems that the logger inside my program uses the logger config in spoon instead of mine :

![image](https://user-images.githubusercontent.com/14107297/112740200-9cefaf80-8fad-11eb-8eaf-005d48a0f918.png)
![image](https://user-images.githubusercontent.com/14107297/112740206-a37e2700-8fad-11eb-82f8-65b438fd787c.png)

I have tried to clear the downloaded spoon jar but the error still remains, I guess the log4j.properties should not be shipped with the jar?

**Comment by monperrus** [comment]
Should be fixed by https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/151 and continuous 
delivery will push a new version to Maven Central.

**Comment by monperrus** [comment]
You can try with new version 1.31, it should be fixed.

**Comment by monperrus** [comment]
See https://repo1.maven.org/maven2/fr/inria/gforge/spoon/labs/gumtree-spoon-ast-diff/1.31/

**Comment by Symbolk** [comment]
> You can try with new version 1.31, it should be fixed.

Confirmed, issue resolved, thanks so much!
