### ISSUE TITLE
Crash on runtime because Spoon is not up to date with Gumtree 

### ISSUE THREAD

**Issue by alkalinan** [SpoonLabs/gumtree-spoon-ast-diff#79]
When I try to execute Gumtree-Spoon, Java returns me this error : 

`java.lang.IllegalArgumentException: Please support the new type class com.github.gumtreediff.actions.model.TreeDelete
	at gumtree.spoon.diff.DiffImpl.lambda$convertToSpoon$0(DiffImpl.java:100)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at gumtree.spoon.diff.DiffImpl.convertToSpoon(DiffImpl.java:102)
	at gumtree.spoon.diff.DiffImpl.<init>(DiffImpl.java:71)
	at gumtree.spoon.AstComparator.compare(AstComparator.java:92)
	at gumtree.spoon.AstComparator.compare(AstComparator.java:84)
	at launcher.Launcher.main(Launcher.java:86)
`

It's explicit enough, I think Gumtree-Spoon need to implement a new structure inside gumtree (TreeDelete) in order to be used.

**Comment by martinezmatias** [comment]
Hi @alkalinan 
We are using gumtree version 2.2.1 which does not include the new features TreeDelete and TreeInsert.
We plan to consider those changes once the new GT version (3) is released.

it seems you are using the gumtree from the GT project's github.

Regards
Matias
